# Generated by Django 5.2.7 on 2025-10-02 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userveterinaria',
            name='es_admin',
        ),
    ]
