# Generated by Django 5.2.6 on 2025-10-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvet', '0002_remove_userveterinaria_es_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('rut_propietario', models.CharField(max_length=12)),
                ('tipo_mascota', models.CharField(max_length=20)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
            ],
        ),
    ]
