# Generated by Django 5.2.7 on 2025-10-03 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvet', '0003_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
