# Generated by Django 5.2.5 on 2025-10-07 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvet', '0004_cita_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='trabajador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
